# Generated by Django 4.2.5 on 2023-10-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('notes', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
