# Generated by Django 4.2.4 on 2023-10-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='dog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.dog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(default='notes', max_length=250),
            preserve_default=False,
        ),
    ]
