# Generated by Django 4.2.4 on 2023-10-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_service_dog_service_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
