# Generated by Django 4.2.5 on 2023-10-05 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('B', 'Bath'), ('W', 'Walk'), ('T', 'Treat'), ('P', 'Playtime')], default='B', max_length=1),
        ),
    ]
